#!/usr/bin/env bash
# Strip Rust-related files from a pizzarr source tree in place.
#
# The CRAN tier ships pure R. This script removes src/, the configure
# scripts, extendr machinery, and related metadata so what's left is
# equivalent to what would be shipped to CRAN.
#
# Used by:
#   tools/cran-build.sh        — on a tmp copy, before R CMD build
#   .github/workflows/rhub.yaml — on the GHA checkout, before run-check
#
# Usage:
#   bash tools/cran-strip.sh [pkg-dir]
#
# Default pkg-dir is $PWD. The script expects DESCRIPTION and NAMESPACE
# in pkg-dir. Uses only POSIX grep/awk — no sed -i portability traps.

set -euo pipefail

PKG_DIR="${1:-$PWD}"
cd "$PKG_DIR"

if [ ! -f DESCRIPTION ] || [ ! -f NAMESPACE ]; then
  echo "ERROR: $PKG_DIR is not an R package root (missing DESCRIPTION or NAMESPACE)" >&2
  exit 1
fi

# Remove Rust/extendr source and build hooks.
rm -rf src/
rm -f configure configure.win
rm -f cleanup cleanup.win
rm -f tools/config.R tools/msrv.R

# DESCRIPTION: drop the multi-line SystemRequirements field and the
# Config/rextendr/version line.
awk '
  /^SystemRequirements:/ { skip = 1; next }
  skip && /^[[:space:]]/ { next }
  { skip = 0; print }
' DESCRIPTION > DESCRIPTION.tmp
mv DESCRIPTION.tmp DESCRIPTION

grep -v '^Config/rextendr/version:' DESCRIPTION > DESCRIPTION.tmp
mv DESCRIPTION.tmp DESCRIPTION

# Replace extendr-wrappers.R with a minimal stub. No DLL exists on the
# CRAN tier, so the only surviving export is zarrs_compiled_features(),
# which errors; is_zarrs_available() catches that and returns FALSE.
if [ -f R/extendr-wrappers.R ]; then
  cat > R/extendr-wrappers.R << 'WRAPPER_EOF'
# Generated by extendr: Do not edit by hand
# Stub for CRAN tier (no Rust shared library)

# nolint start

#' @usage NULL
NULL

#' Return compiled zarrs feature flags as a character vector.
#'
#' On the CRAN tier (pure R), this function always errors. The error
#' is caught by \code{is_zarrs_available()}, which returns \code{FALSE}.
#' @export
zarrs_compiled_features <- function() {
  stop("zarrs backend not compiled (pure R install)")
}

# nolint end
WRAPPER_EOF
fi

# NAMESPACE: drop useDynLib, drop exports of Rust-only zarrs_* functions.
# zarrs_compiled_features is the only zarrs_ export that survives.
grep -v '^useDynLib' NAMESPACE > NAMESPACE.tmp
mv NAMESPACE.tmp NAMESPACE

awk '
  /^export\(zarrs_/ && !/zarrs_compiled_features/ { next }
  { print }
' NAMESPACE > NAMESPACE.tmp
mv NAMESPACE.tmp NAMESPACE

# Rust-only topics: not exported and not documented on the CRAN tier.
# This list drives both the Rd removal and the \link{} rewrite below, so the
# two cannot drift apart. It is every export(zarrs_*) in NAMESPACE except
# zarrs_compiled_features, which survives as the stub above.
ZARRS_ONLY_TOPICS="zarrs_close_store zarrs_create_array zarrs_get_key
zarrs_get_subset zarrs_node_exists zarrs_open_array_metadata
zarrs_runtime_info zarrs_set_codec_concurrent_target
zarrs_set_http_batch_range_requests zarrs_set_nthreads zarrs_set_subset"

# Remove Rd pages for Rust-only functions.
for topic in $ZARRS_ONLY_TOPICS; do
  rm -f "man/${topic}.Rd"
done

# Surviving Rd pages still \link{} to the topics just removed, which fails
# "checking Rd cross-references" with a missing-link WARNING. Unwrap those
# links to their display text, leaving any surrounding \code{} intact:
# \code{\link[=zarrs_get_subset]{zarrs_get_subset()}} -> \code{zarrs_get_subset()}
# Match \link[=topic]{...} for any dropped topic, for the skip test below.
DROPPED_LINK_RE="$(echo $ZARRS_ONLY_TOPICS | tr " " "|")"
DROPPED_LINK_RE="\\link\[=($DROPPED_LINK_RE)\]"

for rd in man/*.Rd; do
  [ -f "$rd" ] || continue
  # Skip files with no link to a dropped topic: most of man/ is untouched.
  grep -Eq "$DROPPED_LINK_RE" "$rd" || continue
  awk -v topics="$ZARRS_ONLY_TOPICS" '
    BEGIN {
      n = split(topics, t, /[ \t\n]+/)
      for (i = 1; i <= n; i++) if (t[i] != "") drop[t[i]] = 1
    }
    {
      line = $0; out = ""
      while ((i = index(line, "\\link")) > 0) {
        out = out substr(line, 1, i - 1)
        rest = substr(line, i + 5)
        if (substr(rest, 1, 2) == "[=") {
          j = index(rest, "]{")
          if (j == 0) { out = out "\\link"; line = rest; continue }
          topic = substr(rest, 3, j - 3)
          rest = substr(rest, j + 2)
        } else if (substr(rest, 1, 1) == "{") {
          topic = ""
          rest = substr(rest, 2)
        } else {
          out = out "\\link"; line = rest; continue
        }
        k = index(rest, "}")
        if (k == 0) { out = out "\\link"; line = rest; continue }
        text = substr(rest, 1, k - 1)
        if (topic == "") topic = text
        out = out ((topic in drop) ? text : "\\link[=" topic "]{" text "}")
        line = substr(rest, k + 1)
      }
      print out line
    }
  ' "$rd" > "$rd.tmp"
  mv "$rd.tmp" "$rd"
done

# Include vignettes in the shipped tarball. They are .Rbuildignored on
# the r-universe tier, so strip that line for the CRAN tier.
if [ -f .Rbuildignore ]; then
  grep -v '^\^vignettes\$' .Rbuildignore > .Rbuildignore.tmp
  mv .Rbuildignore.tmp .Rbuildignore
fi

# Drop tools/ if now empty.
rmdir tools 2>/dev/null || true
