#!/usr/bin/env bash
# Build a CRAN-ready tarball without the Rust src/ directory.
#
# The CRAN tier ships pure R — no Rust compilation. This script
# copies the package tree, strips Rust-related files, and runs
# R CMD build on the clean copy.
#
# Usage:
#   bash tools/cran-build.sh
#
# Output:
#   pizzarr_<version>.tar.gz in the current directory

set -euo pipefail

PKG_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PKG_NAME="$(grep '^Package:' "$PKG_DIR/DESCRIPTION" | sed 's/Package: *//')"
PKG_VERSION="$(grep '^Version:' "$PKG_DIR/DESCRIPTION" | sed 's/Version: *//')"

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "=== Building CRAN tarball for ${PKG_NAME} ${PKG_VERSION} ==="
echo "    Source: $PKG_DIR"
echo "    Temp:   $TMPDIR"

# Copy package tree, skipping large build artifacts.
# We delete src/ entirely below, so skip the Rust target dir now.
mkdir -p "$TMPDIR/$PKG_NAME"
for item in "$PKG_DIR"/*; do
  base="$(basename "$item")"
  case "$base" in
    .git) continue ;;
    src)
      # Copy src/ without rust/target (can be >1 GB)
      mkdir -p "$TMPDIR/$PKG_NAME/src"
      for sub in "$item"/*; do
        subbase="$(basename "$sub")"
        if [ "$subbase" = "rust" ]; then
          mkdir -p "$TMPDIR/$PKG_NAME/src/rust"
          for rsub in "$sub"/*; do
            rsubbase="$(basename "$rsub")"
            [ "$rsubbase" = "target" ] && continue
            cp -r "$rsub" "$TMPDIR/$PKG_NAME/src/rust/"
          done
        else
          cp -r "$sub" "$TMPDIR/$PKG_NAME/src/"
        fi
      done
      ;;
    *) cp -r "$item" "$TMPDIR/$PKG_NAME/" ;;
  esac
done
# Copy dotfiles
for item in "$PKG_DIR"/.[!.]*; do
  base="$(basename "$item")"
  [ "$base" = ".git" ] && continue
  cp -r "$item" "$TMPDIR/$PKG_NAME/" 2>/dev/null || true
done

cd "$TMPDIR/$PKG_NAME"

# Strip Rust-related files
rm -rf src/
rm -f configure configure.win
rm -f cleanup cleanup.win
rm -f tools/config.R tools/msrv.R

# Remove SystemRequirements from DESCRIPTION (Rust not needed)
# Field may span multiple lines (continuation lines start with whitespace)
sed -i '/^SystemRequirements:/,/^[^ \t]/{/^SystemRequirements:/d;/^[ \t]/d;}' DESCRIPTION

# Remove Config/rextendr/version from DESCRIPTION
sed -i '/^Config\/rextendr\/version:/d' DESCRIPTION

# Remove the extendr-wrappers.R (no shared library to call into).
# The zarrs_compiled_features() .Call wrapper would error without the
# DLL, but is_zarrs_available() catches that and returns FALSE.
# Keep the file but strip the @useDynLib directive so R CMD check
# does not complain about a missing DLL.
if [ -f R/extendr-wrappers.R ]; then
  # Replace the file with a minimal stub that doesn't load a DLL
  cat > R/extendr-wrappers.R << 'WRAPPER_EOF'
# Generated by extendr: Do not edit by hand
# Stub for CRAN tier (no Rust shared library)

# nolint start

#' @usage NULL
NULL

#' Return compiled zarrs feature flags as a character vector.
#'
#' On the CRAN tier (pure R), this function always errors. The error
#' is caught by \code{is_zarrs_available()}, which returns \code{FALSE}.
#' @export
zarrs_compiled_features <- function() {
  stop("zarrs backend not compiled (pure R install)")
}

# nolint end
WRAPPER_EOF
fi

# Remove useDynLib from NAMESPACE (no shared library on CRAN tier)
sed -i '/^useDynLib/d' NAMESPACE

# Remove exports for Rust-only functions (keep zarrs_compiled_features, which is stubbed)
sed -i '/^export(zarrs_/{ /zarrs_compiled_features/!d; }' NAMESPACE

# Remove Rd files for Rust-only functions (no code to back them on CRAN)
rm -f man/zarrs_close_store.Rd man/zarrs_create_array.Rd \
      man/zarrs_get_subset.Rd man/zarrs_node_exists.Rd \
      man/zarrs_open_array_metadata.Rd man/zarrs_runtime_info.Rd \
      man/zarrs_set_codec_concurrent_target.Rd \
      man/zarrs_set_http_batch_range_requests.Rd \
      man/zarrs_set_nthreads.Rd man/zarrs_set_subset.Rd

# Include vignettes in CRAN tarball (excluded in .Rbuildignore for r-universe)
sed -i '/^\^vignettes\$/d' .Rbuildignore

# Remove tools/ if now empty
rmdir tools 2>/dev/null || true

echo "=== Running R CMD build ==="
cd "$TMPDIR"

# Find R on PATH or use R_HOME
if command -v R &> /dev/null; then
  R_CMD="R"
elif [ -n "${R_HOME:-}" ]; then
  R_CMD="${R_HOME}/bin/R"
else
  # Common Windows location
  R_CMD="$(ls -d /c/Users/*/AppData/Local/Programs/R/R-*/bin/R.exe 2>/dev/null | tail -1)"
  if [ -z "$R_CMD" ]; then
    echo "ERROR: R not found. Set R_HOME or add R to PATH."
    exit 1
  fi
fi

"$R_CMD" CMD build "$PKG_NAME"

# Copy tarball to original directory
cp "${PKG_NAME}_${PKG_VERSION}.tar.gz" "$PKG_DIR/"

echo "=== Done: ${PKG_NAME}_${PKG_VERSION}.tar.gz ==="
