# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_pizzarr_wrappers", use_symbols = TRUE, package_name = "pizzarr")

#' @usage NULL
#' @useDynLib pizzarr, .registration = TRUE
NULL

#' Return compiled zarrs feature flags as a character vector.
#'
#' Called once at `.onLoad` to populate `.pizzarr_env$zarrs_available`.
#' The feature list is determined at compile time via `cfg!` checks.
#' @export
zarrs_compiled_features <- function() .Call(wrap__zarrs_compiled_features)


# nolint end
