# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_pizzarr_wrappers", use_symbols = TRUE, package_name = "pizzarr")

#' @usage NULL
#' @useDynLib pizzarr, .registration = TRUE
NULL

#' Return compiled zarrs feature flags as a character vector.
#'
#' Called once at `.onLoad` to populate `.pizzarr_env$zarrs_available`.
#' The feature list is determined at compile time via `cfg!` checks.
#' @export
zarrs_compiled_features <- function() .Call(wrap__zarrs_compiled_features)

#' Check whether a node exists at the given path in a zarrs store.
#'
#' Open (or reuse) the store at `store_url`, then probe for V3 and V2
#' metadata keys at `path`.
#'
#' # Arguments
#'
#' * `store_url` - Filesystem path or URL to the store root.
#' * `path` - Path within the store (e.g. `"group1/array1"` or `""` for root).
#'
#' # Errors
#'
#' Returns an R error if the store cannot be opened or a storage I/O
#' error occurs while probing keys.
#' @export
zarrs_node_exists <- function(store_url, path) .Call(wrap__zarrs_node_exists, store_url, path)

#' Close (remove) a cached store handle.
#'
#' Returns `TRUE` if the store was in the cache and was removed,
#' `FALSE` if it was not cached.
#' @export
zarrs_close_store <- function(store_url) .Call(wrap__zarrs_close_store, store_url)

#' Open a zarrs array and return its metadata as an R list.
#'
#' Returns a named list with `shape`, `chunks`, `dtype`, `r_type`,
#' `fill_value_json`, `zarr_format`, and `order`.
#'
#' @param store_url Filesystem path or URL to the store root.
#' @param array_path Path to the array within the store.
#' @export
zarrs_open_array_metadata <- function(store_url, array_path) .Call(wrap__zarrs_open_array_metadata, store_url, array_path)

#' Return runtime information about the zarrs backend.
#'
#' Returns a named list with `codec_concurrent_target`,
#' `store_cache_entries`, and `compiled_features`.
#' @export
zarrs_runtime_info <- function() .Call(wrap__zarrs_runtime_info)

#' Set the zarrs codec concurrent target.
#'
#' Controls the number of concurrent codec operations zarrs uses
#' within a single array operation.
#'
#' @param n Positive integer.
#' @export
zarrs_set_codec_concurrent_target <- function(n) .Call(wrap__zarrs_set_codec_concurrent_target, n)

#' Get a contiguous subset of an array.
#'
#' Returns a named list with `data` (numeric, integer, or logical vector)
#' and `shape` (integer vector). Ranges are 0-based, exclusive stop.
#'
#' @param store_url Filesystem path or URL to the store root.
#' @param array_path Path to the array within the store.
#' @param ranges R list of length-2 integer vectors `c(start, stop)`.
#' @param concurrent_target Optional codec concurrency override.
#' @export
zarrs_get_subset <- function(store_url, array_path, ranges, concurrent_target) .Call(wrap__zarrs_get_subset, store_url, array_path, ranges, concurrent_target)

#' Set a contiguous subset of an array from R data.
#'
#' Returns `true` on success. Ranges are 0-based, exclusive stop.
#' Data must be a flat vector in C-order (row-major).
#'
#' @param store_url Filesystem path or URL to the store root.
#' @param array_path Path to the array within the store.
#' @param ranges R list of length-2 integer vectors `c(start, stop)`.
#' @param data R vector (numeric, integer, or logical).
#' @param concurrent_target Optional codec concurrency override.
#' @export
zarrs_set_subset <- function(store_url, array_path, ranges, data, concurrent_target) .Call(wrap__zarrs_set_subset, store_url, array_path, ranges, data, concurrent_target)

#' Create a new zarr array and write its metadata to the store.
#'
#' Returns the same metadata list as `zarrs_open_array_metadata`.
#'
#' @param store_url Filesystem path to the store root.
#' @param array_path Path to the array within the store.
#' @param shape Integer vector of array dimensions.
#' @param chunks Integer vector of chunk dimensions.
#' @param dtype V3-style data type name (e.g., "float64", "int32").
#' @param codec_preset Compression preset: "none", "gzip", "blosc", or "zstd".
#' @param fill_value Scalar fill value (numeric, integer, logical, or NA).
#' @param attributes_json JSON string of array attributes.
#' @param zarr_format Integer: 2 for V2, 3 for V3.
#' @export
zarrs_create_array <- function(store_url, array_path, shape, chunks, dtype, codec_preset, fill_value, attributes_json, zarr_format) .Call(wrap__zarrs_create_array, store_url, array_path, shape, chunks, dtype, codec_preset, fill_value, attributes_json, zarr_format)


# nolint end
