# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_pizzarr_wrappers", use_symbols = TRUE, package_name = "pizzarr")

#' @usage NULL
#' @useDynLib pizzarr, .registration = TRUE
NULL

#' Return compiled zarrs feature flags as a character vector.
#'
#' Called once at `.onLoad` to populate `.pizzarr_env$zarrs_available`.
#' The feature list is determined at compile time via `cfg!` checks.
#' @export
zarrs_compiled_features <- function() .Call(wrap__zarrs_compiled_features)

#' Check whether a node exists at the given path in a zarrs store.
#'
#' Open (or reuse) the store at `store_url`, then probe for V3 and V2
#' metadata keys at `path`.
#'
#' # Arguments
#'
#' * `store_url` - Filesystem path or URL to the store root.
#' * `path` - Path within the store (e.g. `"group1/array1"` or `""` for root).
#'
#' # Errors
#'
#' Returns an R error if the store cannot be opened or a storage I/O
#' error occurs while probing keys.
#' @export
zarrs_node_exists <- function(store_url, path) .Call(wrap__zarrs_node_exists, store_url, path)

#' Close (remove) a cached store handle.
#'
#' Returns `TRUE` if the store was in the cache and was removed,
#' `FALSE` if it was not cached.
#' @export
zarrs_close_store <- function(store_url) .Call(wrap__zarrs_close_store, store_url)


# nolint end
